remote_theme: just-the-docs/just-the-docs
markdown: kramdown
has_toc: false

just_the_docs:
  logo: "/home/asset/images/am_logo_large_white.png"
  nav_enabled: true
  search_enabled: true
  heading_anchors: true
  collections:
    manual:
      output: true
      permalink: /:path/
